### ISSUE TITLE
User Input Malformed

### ISSUE THREAD

**Issue by drthanwho** [custom-components/remote_homeassistant#140] opened 2021-10-18 18:30 UTC
Adding the component with all entities works but trying to select only specfic sensors to add I get a `User Input Malformed` errors 
![image](https://user-images.githubusercontent.com/22405505/137786706-f1ce1702-0197-4f64-ae09-8ba184259369.png)

**Comment by matata86** [comment] 2021-11-03 18:12
Same problem for me

**Comment by BCsabaEngine** [comment] 2021-11-03 22:02
Same problem.

**Comment by Flipsoo** [comment] 2021-11-04 16:49
Same here with hassio 2021.11 when checkboxes are checked

**Comment by ranrinc** [comment] 2021-11-07 14:42
having the same problem

**Comment by pauerbuk** [comment] 2021-11-07 15:23
Same problem.

**Comment by pironic** [comment] 2021-11-07 15:27
an unsupported work around would be to edit the `.storage/core.config_entities` to your liking... changes there also require a restart of home-assistant once saved. use at your own risk. that being said.. it worked for me. :)

**Comment by florianec** [comment] 2021-11-09 20:09
This may be fixed with 2021.11.3 when released https://github.com/home-assistant/frontend/pull/10585

**Comment by tsekov** [comment] 2021-11-10 21:02
I got the same when trying to config integration via Configuration -> Integrations -> Remote Home Assistant -> Configuration wizard.
When configured via YAML (I include the same entities as I try to include via the GUI) it works and even populates the integration wizard in Configuration -> Integrations -> Remote Home Assistant -> Configuration. It populates the wizard, but the same entities remain unselected in the wizard and can be selected a second time, which when done - duplicates them in the wizard and brings back this "User input malformed" error.

**Comment by florianec** [comment] 2021-11-12 11:34
2021.11.3 fixed this for me

**Comment by Deedikjupijn** [comment] 2023-05-24 18:57
Sadly the issue is still there, I am unable to remove the included domain cause it doesnt exsist anymore, maybe it would fix it if there would be an option to just enable the vieuw of all available domains not just the ones available, or another option to clear the domains (I do not want to go trough the process of setup again cause I have a lot of entities setup and I dont want to go all over those again... Good luck if anyone bothers trying to fix it :D
<img width="425" alt="image" src="https://github.com/custom-components/remote_homeassistant/assets/67846839/89f4e3a1-fa80-41df-b05d-f6185738f3bf">

**Comment by Deedikjupijn** [comment] 2023-05-25 06:53
For me it got fixed yesterday, when finally deciding to reintegrating it the menu changed to this (see picture) and that allowed me to just (un)check what options I would like to. This had the option that was missing with the other menu in there.
![Screenshot_2023-05-25-08-41-25-292_io.homeassistant.companion.android.jpg](https://github.com/custom-components/remote_homeassistant/assets/67846839/d35804e4-571c-4dc8-89a0-0b8467a45575)

**Closed** 2024-06-21 16:07 UTC
