### ISSUE TITLE
States are not updating in lovelace

### ISSUE THREAD

**Issue by noiseboy303** [custom-components/remote_homeassistant#109] opened 2021-02-15 03:17 UTC
Hi guys, each time I hit a button in lovelace, the entity is responding normally but then, it's not showing the new state of the entity and then, it won't respond to new commands until I reload the integration.

I am on the Master version, on Raspi 4, Core 2021.2.3, supervisor-2021.02.9

**Comment by noiseboy303** [comment] 2021-02-17 00:51
And now, it takes about 8 seconds for the "button" to do the action?!  What is happening... anybody?

Thanks again for your great work!

**Comment by kmge** [comment] 2021-02-22 15:08
Same here

**Comment by postlund** [comment] 2021-02-22 16:57
We will need additional logs to troubleshoot this. Have you checked the error log to start with?

**Comment by noiseboy303** [comment] 2021-02-22 19:45
Sorry postlund, It has been fixed 2 days ago, I was just being dumb!  I finally figured out where to add the "state_changed and the service_registered". Thanks for the great Add on!!! works amazing!

**Comment by noiseboy303** [comment] 2021-02-22 19:49
> Same here

Kmge, did you add those 2 (state_changed & service_registered) in the add-on, Configuration Subscribed events (Step 4) ?

**Comment by postlund** [comment] 2021-02-22 20:37
@noiseboy303 Great to here that it works. If you are running the master version of the component, it is not needed though. Are you sure you are not running the latest released version?

**Comment by noiseboy303** [comment] 2021-02-22 21:06
@postlund I can do a quick test and try to reinstall the component (make sure that I have the Master version and will report in the next 10 minutes...

**Comment by noiseboy303** [comment] 2021-02-22 21:24
@postlund , Just tried again the Master Version and it's not working, re-added the 2 Subscribed events and it's working again?!

**Comment by kmge** [comment] 2021-02-23 09:52
> 
> 
> > Same here
> 
> Kmge, did you add those 2 (state_changed & service_registered) in the add-on, Configuration Subscribed events (Step 4) ?

That was the problem. Now it's working fine! Thanks!

**Comment by noiseboy303** [comment] 2021-02-23 21:10
> > > Same here
> > 
> > 
> > Kmge, did you add those 2 (state_changed & service_registered) in the add-on, Configuration Subscribed events (Step 4) ?
> 
> That was the problem. Now it's working fine! Thanks!

Sweet! You are welcome!

**Comment by mantaalex** [comment] 2021-02-28 01:33
> > Same here
> 
> Kmge, did you add those 2 (state_changed & service_registered) in the add-on, Configuration Subscribed events (Step 4) ?

tx for this fix

**Comment by postlund** [comment] 2021-03-04 21:46
I believe this should work with latest release in HACS without the need of manually listening to the events. But I'll close this as the problem is resolved.

**Closed by postlund** 2021-03-04 21:46 UTC
