### ISSUE TITLE
Remote Nodes not working after HA update 2023.5.1

### ISSUE THREAD

**Issue by sag007** [custom-components/remote_homeassistant#230] opened 2023-05-05 03:27 UTC
Hey Guys,

I just installed the 2023.5.1 update to Home Assistant and the remote assistant addon stopped working. This would have to one of the most handy addons to HA I have found to date so to have it fail is a pain.

I'm just wondering if anyone else has experienced this issue since the update?

Nathan

**Comment by RMMTSLLP** [comment] 2023-05-05 07:40
Yes I found similar issue when upgrading to 2023.5.0  ...................... Frustrating

Roger

**Comment by RMMTSLLP** [comment] 2023-05-05 08:07
What I did find is that if just the node is running 2023.5.1 and the main instance 2023.4.7 all is OK I don't know if this helps with solution.

Roger

**Comment by lukas-hetzenecker** [comment] 2023-05-05 09:35
I did not find a note in the [developer blog](https://developers.home-assistant.io/blog/) about any breaking changes, so I'll try to see myself if I can reproduce the issue when upgrading the instances (should be able to get to that some point next week)

**Comment by BCsabaEngine** [comment] 2023-05-06 23:08
I have the same issue after upgrade. Remote status is connecting instead of connect. And remote entities are unavailable.
Can I help you to detect/test anything?

**Comment by nextxpert** [comment] 2023-05-08 05:27
I have the same issue since the uppgrade to 2023.5.0. Remote status is connecting.

**Comment by sag007** [comment] 2023-05-11 00:28
Hey Guys,

I can also confirm, I rolled the main HA instance of remote HA back to 3.7 and all started working again. The remote nodes are still running 3.8.

Hope this helps in diagnosing the issues.

Nathan

**Comment by tmoore22** [comment] 2023-05-15 10:53
Nudge, we stuck upgrading now :(

**Comment by matzzzz** [comment] 2023-05-15 11:36
Hi,
I just want to tell you that it's not a general problem for all with remote HA instantsis, I have two which both are upgraded to 23.5.3 and is fully functional. They have been upgraded in the order the releases have been released i.e. 23.4.6 -> 23.5.0 -> 23.5.1 .... 23.5.3. The remote instances are Rpi with HA OS and main HA a Proxmox VM with HA OS

**Comment by tmoore22** [comment] 2023-05-15 16:05
not working upgrade 2023.4.4 -> 2023.5.0 and above. I just retried to confirm!!

```python
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 253, in setup_components_and_platforms
    await remote.async_connect()
  File "/config/custom_components/remote_homeassistant/__init__.py", line 430, in async_connect
    device_registry = await dr.async_get_registry(self._hass)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'
```

**Comment by tmoore22** [comment] 2023-05-15 16:25
simple, because of depreciated 'async_get_registry'. remove in PR#91928:
[https://github.com/home-assistant/core/pull/91928](https://github.com/home-assistant/core/pull/91928)

**Comment by BCsabaEngine** [comment] 2023-05-15 16:31
> not working upgrade 2023.4.4 -> 2023.5.0 and above. I just retried to confirm!!
> 
> ```python
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/remote_homeassistant/__init__.py", line 253, in setup_components_and_platforms
>     await remote.async_connect()
>   File "/config/custom_components/remote_homeassistant/__init__.py", line 430, in async_connect
>     device_registry = await dr.async_get_registry(self._hass)
> AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'
> ```

Is this the reason of error? Should simple change e it to async_get()?

**Comment by BCsabaEngine** [comment] 2023-05-15 16:49
Checked! Upgrade to HassRemote 3.8 solves the problem.

**Comment by nextxpert** [comment] 2023-05-15 18:48
How do you upgrade to HassRemote 3.8?

**Comment by tmoore22** [comment] 2023-05-15 18:55
Confirmed, issue was fixed in 3.7 .. upgrade to latest version (3.8)
https://github.com/custom-components/remote_homeassistant/releases/tag/3.7

**Comment by tmoore22** [comment] 2023-05-15 18:56
> How do you upgrade to HassRemote 3.8?

https://github.com/custom-components/remote_homeassistant/releases/tag/3.8
download and re-install, delete old folder in custom_components first

**Comment by RMMTSLLP** [comment] 2023-05-16 06:16
Thanks guys update to 3.8 resolved the issues

**Comment by tmoore22** [comment] 2023-05-16 12:26
> Hey Guys,
> 
> I just installed the 2023.5.1 update to Home Assistant and the remote assistant addon stopped working. This would have to one of the most handy addons to HA I have found to date so to have it fail is a pain.
> 
> I'm just wondering if anyone else has experienced this issue since the update?
> 
> Nathan

@sag007 please can you close this as resolved? you were the initiator, and it helps the project :)

**Comment by lukas-hetzenecker** [comment] 2023-05-16 13:05
closed, as this is resolved by updating to the latest release (that also explains why I could not reproduce it :) )

**Closed by lukas-hetzenecker** 2023-05-16 13:05 UTC
