### ISSUE TITLE
Camera stream not working

### ISSUE THREAD

**Issue by bbbenji** [custom-components/remote_homeassistant#29] opened 2019-12-29 08:55 UTC
I am not sure if this is a limitation of home-assistant-remote, or perhaps an issue on my end. However, I am unable to get a camera stream working on the master instance of my Home Assistant. The console shows the following error, basically a 404: https://pastebin.com/raw/EUP8dVYj

```
{code: "start_stream_failed", message: "Camera not found"}
camera.brz_side:1 GET https://ha-instance.com/api/camera_proxy_stream/camera.brz_side?token=XXXX 404
```

EDIT: Taking a closer look at the README, it seems that only remote __states__ are populated? So no luck getting the camera working I assume.

**Comment by polcape** [comment] 2020-04-07 16:29
Hi, 

I have the same problem

**Comment by henrikhjelm** [comment] 2020-05-09 23:38
any news on this ? 
i only get a "404: Not Found"

**Comment by henrikhjelm** [comment] 2020-05-17 18:30
any news about adding camera support ?

**Comment by x2concepts** [comment] 2020-06-03 16:37
is this even possible at all?

**Comment by lukas-hetzenecker** [comment] 2020-06-03 18:05
Sorry, but I don't think this will ever be possible. The camera returns the link to the stream in the `entity_picture` attribute. 
The component would now have to proxy the complete camera stream from the remote instance. Would be quite cumbersome to implement, and publish it on the master. 
Any takers? :)

**Comment by meichthys** [comment] 2022-05-13 13:22
#129 is a duplicate of this.

**Closed** 2024-02-21 15:29 UTC
Labels: bug, enhancement

**Comment by maxlyth** [comment] 2025-11-30 21:14
My use-case for Remote_HomeAssistant is inverted from design as I am not sending sensor data to a master but filtering a subset of the master to a slave that serves dashboards. I have thousands of entities in the master that mostly drive automations, templates, groups, bayesians but the source data is irrelevant for dashboards but overwhelms the Android 8-10 hardware that is dominant for wall panels.

My implementation filters 4000+ entities to under 100 while still providing full control of lights, climate, alarms, switches etc. I also was frustrated by lack of artwork for media_players and cameras without also setting them up on the slave, even though their entities were mirrored.

My solution is not ideal but as I use Caddy as a reverse proxy (same would work for Traefik or NGinX), I set a matcher to proxy requests for `/api/media_player_proxy/*` and `/api/camera_proxy/*`directly to the master. All other requests go to the RHA server. This fixes my issues without setting up duplicate integrations on the slave.

I think RHS could register API handlers to proxy requests to the master without an 3rd-party proxy but the functionality only makes sense for a use-case like mine and I'm not sure it is common enough to warrant the dev and support.
