### ISSUE TITLE
Camera integration - no streaming

### ISSUE THREAD

**Issue by GitKiller-HA** [custom-components/remote_homeassistant#129] opened 2021-09-15 20:32 UTC
Hi All,

I integrate two HA with remote_homeassistant and its grate!!! Thank You.
But when I tried integrate camera there is no live streaming on the second HA. It is possible integrate camera live streaming via remote_homeassistant ?

Regards,
Grzegorz

**Comment by lpt2007** [comment] 2022-02-28 16:06
Hi,

Did you solve this problem?

I have a same problem with my vacuum camera map. On primary HA I can see vacuum live map on remote HA I get error "entity not available".

**Comment by larry-glz** [comment] 2022-03-02 01:39
This integration is great. I also have the issue where the remote cameras do not stream to the main instance. I noticed the name of the entity in the main instance (camera.rancho_glz_driveway) is not the same as the name in the api call for the camera proxy (camera.driveway). Maybe this helps the devs debug the issue. Thanks
![Uploading FF38E1C6-E73D-4F52-845A-150F9EC7CB54.jpeg…]()

**Comment by Vispen74** [comment] 2022-03-29 13:27
Any progress on this one? Can I help uploading logs or try something?

**Comment by meichthys** [comment] 2022-05-13 13:16
It seems to be an issue with the `Entity Prefix`. Have you tried it without using an entity prefix in the configuration? If that works, then we probably need to update things to properly take the entity prefix into account when determining the entity_picture value on the client instance.

**Comment by meichthys** [comment] 2022-05-13 13:21
This is also a duplicate of #29

**Comment by meichthys** [comment] 2022-05-13 13:23
Looks like this is not possible: https://github.com/custom-components/remote_homeassistant/issues/29#issuecomment-638367533

**Comment by Apeiv** [comment] 2022-09-14 15:21
any news about this bug?

Thanks for your work.

**Comment by rtjdamen** [comment] 2023-05-19 15:28
I am facing the same issue, is this something planned to be integrated in the future releases? If it does not work shy not exclude camera as an option to select?

**Comment by larry-glz** [comment] 2023-05-20 01:42
You can exclude the camera domain in the “configuration.”

**Closed** 2024-06-21 16:02 UTC
